### ISSUE TITLE
Change language 'no' to 'nb'

### ISSUE THREAD

**Issue by danmichaelo** [inventaire/inventaire-i18n#2]
Would you mind changing the language code `no` (Norwegian) to `nb` (Norwegian Bokmål)? Norwegian consists of two written languages that are similar, but different (`nb`: Bokmål and `nn`: Nynorsk). Someone might want to create a Nynorsk translation at some point. For this reason, we try to avoid using the language code `no`. At Wikidata, for instance, we only use `nb` and `nn`. At Wikipedia, we are for historical reasons stuck with `no.wikipedia.org` as the domain for Bokmål, but `nb` is used as the language code.

I don't create a PR since I expect that changes at Transifex are also needed.

**Comment by maxlath** [comment]
done!
- `no` translations on Transifex were transfered to `nb`
- `no` language code was replaced by `nb` (db17324) (which indeed give us access to wikidata property labels translations \o/)
- [`wikidata-lang` now has an entry for `nb`](https://github.com/inventaire/wikidata-lang/commit/a4c1f61), and the [server](https://github.com/inventaire/inventaire/commit/f204e0d1) and [client](https://github.com/inventaire/inventaire-client/commit/aaf9e840) were updated to use it

**Comment by maxlath** [comment]
regarding data, I retro-actively converted `no` labels into `nb` labels, but [some editions are still linking to "Norwegian" (wd:Q9043)](https://query.inventaire.io/embed.html#SELECT%20*%20{%0A%20%20%3Fitem%20wdt%3AP407%20wd%3AQ9043%20.%0A%20%20%3Fitem%20wdt%3AP1476%20%3Ftitle%20.%0A}%0ALIMIT%20100): should those also be all changed to [bokmål (wd:Q25167)](https://www.wikidata.org/wiki/Q25167)?

**Comment by danmichaelo** [comment]
> regarding data, I retro-actively converted `no` labels into `nb` labels, but [some editions are still linking to "Norwegian" (wd:Q9043)](https://query.inventaire.io/embed.html#SELECT%20*%20%7B%0A%20%20%3Fitem%20wdt%3AP407%20wd%3AQ9043%20.%0A%20%20%3Fitem%20wdt%3AP1476%20%3Ftitle%20.%0A%7D%0ALIMIT%20100): should those also be all changed to [bokmål (wd:Q25167)](https://www.wikidata.org/wiki/Q25167)?

Thanks, I can check those! One is even `en` ("Equal Democracies?"). Some might be `nn` (nynorsk), but most are likely `nb`.
